#!/bin/bash
# needs AZBLOB_ACCOUNTNAME_TEST, AZBLOB_ACCOUNTKEY_TEST, 
# AZBLOB_CONTAINER_TEST, AZBLOB_BLOB_TEST, AZANONBLOB_CONTAINER_TEST, AZANONBLOB_BLOB_TEST

# anonymous access
export AZBLOB_ACCOUNTNAME=$AZBLOB_ACCOUNTNAME_TEST
rm -f $AZANONBLOB_BLOB_TEST
azblob download $AZANONBLOB_CONTAINER_TEST $AZANONBLOB_BLOB_TEST
azblob download $AZANONBLOB_CONTAINER_TEST $AZANONBLOB_BLOB_TEST --dontreplace
rm -f $AZANONBLOB_BLOB_TEST
export AZBLOB_ACCOUNTNAME=removed
azblob -n $AZBLOB_ACCOUNTNAME_TEST download $AZANONBLOB_CONTAINER_TEST $AZANONBLOB_BLOB_TEST
rm -f $AZBLOB_BLOB_TEST
export AZBLOB_ACCOUNTNAME=$AZBLOB_ACCOUNTNAME_TEST
export AZBLOB_ACCOUNTKEY=$AZBLOB_ACCOUNTKEY_TEST
azblob download $AZBLOB_CONTAINER_TEST $AZBLOB_BLOB_TEST
rm -f $AZBLOB_BLOB_TEST
export AZBLOB_ACCOUNTNAME=removed
export AZBLOB_ACCOUNTKEY=removed
azblob -n $AZBLOB_ACCOUNTNAME_TEST -k $AZBLOB_ACCOUNTKEY_TEST download $AZBLOB_CONTAINER_TEST $AZBLOB_BLOB_TEST
azblob -n $AZBLOB_ACCOUNTNAME_TEST -k $AZBLOB_ACCOUNTKEY_TEST download $AZBLOB_CONTAINER_TEST $AZBLOB_BLOB_TEST --dontreplace
azblob -n $AZBLOB_ACCOUNTNAME_TEST -k $AZBLOB_ACCOUNTKEY_TEST list $AZBLOB_CONTAINER_TEST

