#!/bin/bash
# needs AZBLOB_ACCOUNTNAME_TEST, AZBLOB_ACCOUNTKEY_TEST, 
# AZBLOB_CONTAINER_TEST, AZBLOB_BLOB_TEST
rm -f $AZBLOB_BLOB_TEST
export AZBLOB_ACCOUNTNAME=$AZBLOB_ACCOUNTNAME_TEST
export AZBLOB_ACCOUNTKEY=$AZBLOB_ACCOUNTKEY_TEST
azblob download $AZBLOB_CONTAINER_TEST $AZBLOB_BLOB_TEST
rm -f $AZBLOB_BLOB_TEST
AZBLOB_ACCOUNTNAME=removed
AZBLOB_ACCOUNTKEY=removed
azblob -n $AZBLOB_ACCOUNTNAME_TEST -k $AZBLOB_ACCOUNTKEY_TEST download $AZBLOB_CONTAINER_TEST $AZBLOB_BLOB_TEST
